// PDF Generator
// Converts letter content to a professional PDF
// Uses PDFKit (no sponsor needed — pure Node.js)

const PDFDocument = require('pdfkit');

function generateLetterPDF(letterData) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 72, size: 'LETTER' });
    const buffers = [];

    doc.on('data', chunk => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    // Header
    doc
      .fontSize(18)
      .font('Helvetica-Bold')
      .text('ImmigAI Legal Document', { align: 'center' });

    doc.moveDown(0.5);
    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor('#888888')
      .text('AI-Generated — For Attorney Review Only | Not Legal Advice', { align: 'center' });

    doc.moveDown(1);
    doc.moveTo(72, doc.y).lineTo(540, doc.y).stroke('#cccccc');
    doc.moveDown(1);

    // Title
    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .fillColor('#000000')
      .text(letterData.title || 'Legal Letter');

    doc.moveDown(0.5);
    doc
      .fontSize(11)
      .font('Helvetica')
      .text(`Date: ${letterData.date || new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);

    doc.moveDown(1.5);

    // Letter content
    doc
      .fontSize(11)
      .font('Helvetica')
      .text(letterData.letterContent || letterData.coverLetterContent || '', {
        lineGap: 4,
        paragraphGap: 10
      });

    // Citations section
    if (letterData.citations && letterData.citations.length > 0) {
      doc.moveDown(1.5);
      doc.moveTo(72, doc.y).lineTo(540, doc.y).stroke('#cccccc');
      doc.moveDown(1);

      doc
        .fontSize(11)
        .font('Helvetica-Bold')
        .text('Legal Citations:');

      doc.moveDown(0.5);
      letterData.citations.forEach(citation => {
        doc
          .fontSize(10)
          .font('Helvetica')
          .text(`• ${citation}`, { indent: 10 });
      });
    }

    // Trust layer footer
    if (letterData.trustLayer) {
      doc.moveDown(1);
      doc.moveTo(72, doc.y).lineTo(540, doc.y).stroke('#cccccc');
      doc.moveDown(0.5);

      const score = letterData.trustLayer.confidenceScore;
      doc
        .fontSize(9)
        .font('Helvetica')
        .fillColor('#666666')
        .text(`Confidence Score: ${score}/100 | Trust Layer: ${letterData.trustLayer.provider}`, { align: 'left' });

      doc.moveDown(0.5);
      doc
        .fontSize(9)
        .text('DISCLAIMER: This document was generated by AI and does not constitute legal advice. Always review with a licensed immigration attorney before use.', {
          lineGap: 2
        });
    }

    doc.end();
  });
}

module.exports = { generateLetterPDF };
